### ISSUE TITLE
Broken links in the readme page

### ISSUE THREAD

**Issue by gireeshpunathil** [OpenLiberty/guide-microprofile-intro#9] opened 2017-09-21 12:35 UTC
Many links are broken in the readme page. For example:

 - `../guides-common//gitclone.adoc`
 - `link:finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[]` (his is actually meant to be link right?)

If no one is not already working on this, I can take a shot at it. Please let me know.

**Comment by yeekangc** [comment] 2017-09-21 13:54
@gireeshpunathil, these are expected.

- For example, we are including/re-using the gitclone.adoc from the guides-common repo hence the first link you mentioned.  When AsciiDoctor runs on the README.adoc, it will pull in the content properly.

- This is not meant to be a link but an include.  If you look at the "source" for the .adoc, you will see that it is an include.  GitHub isn't displaying the README.adoc properly as intended.  You can cross check with what is shown at http://openliberty.io/guides/microprofile-intro.html or preview with AsciiDoctor yourself.

We use AsciiDoc as the format for the guides.  They are named README.adoc in the repos.  GitHub supports .adoc and will show the README.adoc as what you see when you navigate to the repos.  Then, it isn't showing (rendering) everything properly.

**Comment by yeekangc** [comment] 2017-09-21 13:54
If you have further feedback, please let us know.  Otherwise, we will close this.  Thank you.

**Comment by gireeshpunathil** [comment] 2017-09-21 13:58
@yeekangc - great, thanks for the super-fast response, and the informative explanation. No, I don't have further questions. Looking forward for contributing to this project!

**Comment by NottyCode** [comment] 2017-09-21 14:08
Hey, hope you don't mind I decided that there is a fix we can do for the first one. In order to do a local build of the readme.adoc you also need to checkout the guides-common repository. Instead if we change:

    :common-includes: ../guides-common/
 to

    :common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master/https://raw.githubusercontent.com/OpenLiberty/guides-common/master/

then it'll build locally. We couldn't do that before everything went live because it wouldn't have built, but it should be possible to do now.

**Comment by gireeshpunathil** [comment] 2017-09-21 14:25
thanks @NottyCode - sure! shall I `do` it as my first contribution here?

**Comment by yeekangc** [comment] 2017-09-21 21:00
Thank you, @gireeshpunathil.  Will look at it.  Please stay tuned.

**Comment by yeekangc** [comment] 2017-10-06 13:40
Using URLs for the includes involves configuring the builds (i.e. AsciiDoctor) to resolve them properly.

**Comment by JunyiSun** [comment] 2017-10-10 15:07
Thank you all. The issue is fixed.

**Closed by JunyiSun** 2017-10-10 15:07 UTC
